version: "3.8"

volumes:
    dbdata:

services:
    mysql:
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
        ports:
            - 1111:3306
        volumes:
            - dbdata:/var/lib/mysql
            - .docker/mysql/entrypoint:/docker-entrypoint-initdb.d/
    laravel.interview:
        build:
            dockerfile: .docker/php/Dockerfile
            context: .
        command: sh -c "composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0"
        ports:
            - 2222:8000
        volumes:
            - ./:/app
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql:3306
